# Generated by Django 5.2 on 2025-04-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeforcesproblem',
            name='division',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
